### ISSUE TITLE
Moving from Travis to GitHub Actions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/crystal#192]
Hello 🙂 

Over the last few months we've been transferring all our CI from Travis to [GitHub Actions (GHA)](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions). We've found that GHA are easier to work with, more reliable, and much much faster. 

Based on our success with GHA and increasing intermittent failures on Travis, we have now decided to try and remove Travis from Exercism's org altogether and [shift everything to GHA](https://github.com/exercism/exercism/issues/5396). This issue acts as a call to action if your track is still using Travis. 

For most CI checks this should be a transposing from Travis' syntax to [GHA syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions), and hopefully quite straightforward (see [this PR for an example](https://github.com/exercism/csharp/pull/1338/files)).  However, if you do encounter any issues doing this, please ask on Slack where lots of us now have experience with GHA, or post a comment here and I'll tag relevant people. This would also make a good Hacktoberfest issue for anyone interested in making their first contribution 🙂 

If you've already switched this track to GHA, please feel free to close this issue and ignore it.

Thanks!

**Comment by ErikSchierboom** [comment]
Thanks to @SleeplessByte, we now have a really nice document and some starting workflows that you can use to help switch to GitHub Actions: https://github.com/exercism/problem-specifications/tree/master/workflows#workflow-templates

**Comment by petertseng** [comment]
I present below a plausible `.github/workflows/tests.yml` file that could be used.
The reason I'm not putting it in a PR is that it doesn't really make sense for me to send it as a PR when there are existing build failures on the track (fetch configlet needs to be fixed, test failures need to be fixed). If the tests for the track get fixed, then I would consider sending the PR.

```yaml
name: Tests
on:
  pull_request:
  push:
    branches:
    - master
    - gha
  schedule:
    # Weekly.
    - cron: "0 0 * * 0"

jobs:
  track-config:
    name: Check track configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch
        run: bin/fetch-configlet
      - name: Lint
        run: bin/configlet lint .
  exercises:
    name: Check exercises
    runs-on: ubuntu-latest
    # idea from https://github.com/actions/starter-workflows/blob/master/ci/crystal.yml
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test
```
