### ISSUE TITLE
Seperate Ci tests

### ISSUE THREAD

**Issue by meatball133** [exercism/crystal#313]
## Background

The ci test is made of 2 parts, one that checks so the "examples" works with the test files, and then another one that compares so the file that the generator would generate is the same test file that is there.
How the current ci is setup is that it first runs the "checks so the "examples" works with the test files" part and then the other part after that.
The ci tests takes around 5 minutes to run at the moment, the test part takes around 4 minutes and the templates part takes 1 minute, but that is with only around 20 exercises having a template. 

Thereby to be able to reduce the amount of time the ci would require to run.
Would it be beneficial if they can run at the same time since they don't rely on each other.

## What?

Separate so the generator test is separate from the exercise tests ci to reduce the amount of time it takes to run.

Here is the current file which handles the tests:

```yml
name: Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Weekly.
    - cron: '0 0 * * 0'

jobs:
  exercises:
    name: Check exercises
    runs-on: ubuntu-latest
    # idea from https://github.com/actions/starter-workflows/blob/master/ci/crystal.yml
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Run tests
        run: make test-exercises
      - name: Run generator tests
        run: ./bin/test_specs
```

## Want more info?

You can write in this issue or message me on slack, my username there is: meatball.
